module.exports = {
  KeyOfConfig: 'config',
  KeyOfSettings: 'settings',
  KeyOfLogger: 'logger',
  KeyOfSchemas: 'schemas',
  KeyOfConnections: 'conns',
  EventOfServerCreate: 'server-create',
  EventOfServerInitializ: 'server-initializ',
  EventOfServerUse: 'server-use',
  EventOfServerRoute: 'server-route',
  EventOfServerStart: 'server-start',
  EventOfServerStop: 'server-stop',
  EventOfServerExit: 'server-exit',
  EventOfSessionStart: 'session-start',
  EventOfSessionEnd: 'session-end',
  ServerOfExpress: 'express',
  ServerOfKoa: 'koa',
  ServerOfKoa2: 'koa2',
  SignalOfExit: ['exit', 'SIGINT', 'SIGUSR2']
}
